# Generated by Django 4.1.5 on 2023-01-12 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billboard', '0004_alter_reply_is_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reply',
            name='is_approved',
            field=models.CharField(choices=[('approved', 'Принят'), ('declained', 'Отклонен'), ('no_status', 'Без статуса')], default='no_status', max_length=16, verbose_name='Одобрение'),
        ),
    ]
