# Generated by Django 4.1.5 on 2023-01-13 11:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('billboard', '0005_alter_reply_is_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='author_ann',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auth_announcements', to=settings.AUTH_USER_MODEL, verbose_name='Автор объявлений'),
        ),
    ]
