# Generated by Django 4.1.5 on 2023-01-14 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billboard', '0006_alter_announcement_author_ann'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='pageviews',
            field=models.PositiveBigIntegerField(default=0, verbose_name='Количество просмотров'),
        ),
    ]
