# Generated by Django 4.1.5 on 2023-01-15 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billboard', '0007_announcement_pageviews'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newsletter',
            old_name='is_ready',
            new_name='is_published',
        ),
    ]
