# Generated by Django 4.1.5 on 2023-01-15 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billboard', '0008_rename_is_ready_newsletter_is_published'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'Профиль пользователя', 'verbose_name_plural': 'Профиль пользователя'},
        ),
        migrations.RenameField(
            model_name='newsletter',
            old_name='text_content',
            new_name='content',
        ),
        migrations.AddField(
            model_name='newsletter',
            name='is_sent',
            field=models.BooleanField(default=True, verbose_name='Отправлено'),
        ),
    ]
