# Generated by Django 4.1.5 on 2023-01-17 10:43

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('billboard', '0011_newsletter_pageviews'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='nickname',
            field=models.CharField(default=None, help_text='Никнейм должен быть буквенно-цифровым и начинаться с букву', max_length=64, unique=True, validators=[django.core.validators.RegexValidator('^[a-zA-Z]+[0-9a-zA-Z]*$', 'Никнейм должен быть буквенно-цифровым и начинаться с букву')], verbose_name='Никнейм'),
        ),
    ]
