# Generated by Django 4.1.5 on 2023-01-17 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billboard', '0014_remove_userprofile_id_alter_userprofile_aboutme_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='verification_code',
            field=models.IntegerField(default=None, max_length=8, verbose_name='Код верификации'),
        ),
    ]
