# Generated by Django 4.1.5 on 2023-01-17 12:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('billboard', '0015_userprofile_verification_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reply',
            name='author_repl',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auth_replies', to=settings.AUTH_USER_MODEL, verbose_name='Автор отликов'),
        ),
    ]
