# Generated by Django 4.1.5 on 2023-01-17 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billboard', '0016_alter_reply_author_repl'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='is_declains_display',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='verification_code',
        ),
    ]
