# Generated by Django 4.1.5 on 2023-01-17 17:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billboard', '0017_remove_userprofile_is_declains_display_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='aboutme',
            field=models.CharField(blank=True, max_length=1024, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='nickname',
            field=models.CharField(help_text='Никнейм должен быть буквенно-цифровым и начинаться с букву', max_length=64, unique=True, validators=[django.core.validators.RegexValidator('^[a-zA-Z]+[0-9a-zA-Z]*$', 'Никнейм должен быть буквенно-цифровым и начинаться с букву')], verbose_name='Никнейм'),
        ),
    ]
