# Generated by Django 4.1.5 on 2023-01-22 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billboard', '0019_alter_announcement_title_alter_newsletter_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='appr_replies_alerts',
            field=models.BooleanField(default=True, verbose_name='Оповещение о принятии отлика'),
        ),
    ]
