# Generated by Django 4.1.5 on 2023-01-25 16:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('billboard', '0021_newsletter_author_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='photoprofile',
            field=models.ImageField(default='', height_field=150, null=True, upload_to='photoprofile/', width_field=150),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='author_news',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auth_newsletters', to=settings.AUTH_USER_MODEL, verbose_name='Автор новостей'),
        ),
    ]
