# Generated by Django 4.1.5 on 2023-01-25 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billboard', '0023_alter_userprofile_photoprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='photoprofile',
            field=models.ImageField(blank=True, null=True, upload_to='photoprofile/'),
        ),
    ]
