# Generated by Django 4.1.5 on 2023-01-25 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billboard', '0024_alter_userprofile_photoprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='photoprofile',
            field=models.ImageField(blank=True, default='photoprofile/photo_default.jpg', null=True, upload_to='photoprofile/'),
        ),
    ]
